In [1]:
import pandas as pd
import numpy as np

In [2]:
# read csv as df
df = pd.read_csv("data_modelling.csv")

In [3]:
df.head()

,Record ID,Company Name,Industry,Carbon Emissions (MT),Water Usage (m^3),Energy Consumption (MWh),Waste Generation (MT),Recycling Rate (%),Supply Chain Sustainability Score,Employee Transportation Mode,...,Water Usage relative to industry average (%),Energy Consumption relative to industry average (%),Waste Generation relative to industry average (%),Energy Tax difference from industry average ($),Carbon Tax difference from industry average ($),Renew-Energy difference from industry (%),Recycling Rate difference from industry (%),Eco-friendly Product Lines difference from industry (%),Sustainable Packaging Initiatives difference from industry,Investment amount difference from industry average ($)
0,1.0,Company_1,IT,41648.0,165790.0,41851.0,11163.0,65.85,55.0,Car,...,-67.376460,64.072112,-13.579389,4555.098068,828.370574,-27.386378,16.207169,-8.304554,0.977703,-8.718245e+05
1,3.0,Company_3,IT,3973.0,450035.0,34379.0,9787.0,27.06,93.0,Car,...,-11.443786,34.778981,-24.231970,3360.761871,-1055.379426,-29.656378,-22.582831,-30.454554,2.977703,1.868472e+06
2,27.0,Company_27,IT,23731.0,627683.0,2598.0,12142.0,31.14,85.0,Public Transport,...,23.513127,-89.814835,-6.000263,-2653.145687,-67.479426,-23.106378,-18.502831,35.045446,-1.022297,-1.702705e+06
3,33.0,Company_33,IT,49146.0,335918.0,43623.0,5646.0,46.68,88.0,Public Transport,...,-33.899305,71.019038,-56.290355,1104.942487,1203.270574,11.623622,-2.962831,-7.584554,-0.022297,2.172012e+06
4,35.0,Company_35,IT,47481.0,21277.0,10315.0,15032.0,28.02,87.0,Walking,...,-95.813191,-59.561209,16.373254,-1360.809555,1120.020574,-21.066378,-21.622831,17.865446,-1.022297,1.778306e+06

In [4]:
numeric_cols = df.select_dtypes(include=[np.number])                                                # Extract numeric columns
numeric_cols = numeric_cols.drop(['Record ID'], axis=1)
df[numeric_cols.columns] = numeric_cols.apply(lambda x: (x - np.mean(x)) / (np.max(x) - np.min(x))) # min-max normalization
df.head()

,Record ID,Company Name,Industry,Carbon Emissions (MT),Water Usage (m^3),Energy Consumption (MWh),Waste Generation (MT),Recycling Rate (%),Supply Chain Sustainability Score,Employee Transportation Mode,...,Water Usage relative to industry average (%),Energy Consumption relative to industry average (%),Waste Generation relative to industry average (%),Energy Tax difference from industry average ($),Carbon Tax difference from industry average ($),Renew-Energy difference from industry (%),Recycling Rate difference from industry (%),Eco-friendly Product Lines difference from industry (%),Sustainable Packaging Initiatives difference from industry,Investment amount difference from industry average ($)
0,1.0,Company_1,IT,0.332973,-0.341798,0.329837,-0.065882,0.264203,-0.246307,Car,...,-0.335673,0.331002,-0.069158,0.467003,0.335371,-0.387468,0.262619,-0.115388,0.088106,-0.176152
1,3.0,Company_3,IT,-0.435968,-0.054628,0.177300,-0.122056,-0.382297,0.397760,Car,...,-0.057014,0.179671,-0.123409,0.344556,-0.427277,-0.419584,-0.365930,-0.423151,0.268335,0.377524
2,27.0,Company_27,IT,-0.032710,0.124848,-0.471490,-0.025914,-0.314297,0.262167,Public Transport,...,0.117144,-0.463992,-0.030558,-0.272009,-0.027319,-0.326913,-0.299818,0.486939,-0.092124,-0.344031
3,33.0,Company_33,IT,0.486006,-0.169919,0.366011,-0.291111,-0.055297,0.313015,Public Transport,...,-0.168888,0.366891,-0.286677,0.113282,0.487151,0.164453,-0.048009,-0.105384,-0.002009,0.438855
4,35.0,Company_35,IT,0.452023,-0.487799,-0.313952,0.092069,-0.366297,0.296065,Walking,...,-0.477346,-0.307699,0.083386,-0.139515,0.453447,-0.298051,-0.350374,0.248231,-0.092124,0.359306

In [5]:
# save as csv
df.to_csv("data_normalized.csv")